# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x04test\"\x1b\n\rtest1_request\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1f\n\x0etest1_response\x12\r\n\x05reply\x18\x01 \x01(\t\"\x1c\n\x0eserver_request\x12\n\n\x02id\x18\x01 \x01(\x05\" \n\x0fserver_response\x12\r\n\x05reply\x18\x01 \x01(\t\"\x1c\n\x0e\x63lient_request\x12\n\n\x02id\x18\x01 \x01(\x05\" \n\x0f\x63lient_response\x12\r\n\x05reply\x18\x01 \x01(\t\"#\n\x15\x62idirectional_request\x12\n\n\x02id\x18\x01 \x01(\x05\"\'\n\x16\x62idirectional_response\x12\r\n\x05reply\x18\x01 \x01(\t2\x9e\x02\n\tTestLearn\x12\x34\n\x05Test1\x12\x13.test.test1_request\x1a\x14.test.test1_response\"\x00\x12@\n\rserver_stream\x12\x14.test.server_request\x1a\x15.test.server_response\"\x00\x30\x01\x12@\n\rclient_stream\x12\x14.test.client_request\x1a\x15.test.client_response\"\x00(\x01\x12W\n\x14\x62idirectional_stream\x12\x1b.test.bidirectional_request\x1a\x1c.test.bidirectional_response\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEST1_REQUEST']._serialized_start=20
  _globals['_TEST1_REQUEST']._serialized_end=47
  _globals['_TEST1_RESPONSE']._serialized_start=49
  _globals['_TEST1_RESPONSE']._serialized_end=80
  _globals['_SERVER_REQUEST']._serialized_start=82
  _globals['_SERVER_REQUEST']._serialized_end=110
  _globals['_SERVER_RESPONSE']._serialized_start=112
  _globals['_SERVER_RESPONSE']._serialized_end=144
  _globals['_CLIENT_REQUEST']._serialized_start=146
  _globals['_CLIENT_REQUEST']._serialized_end=174
  _globals['_CLIENT_RESPONSE']._serialized_start=176
  _globals['_CLIENT_RESPONSE']._serialized_end=208
  _globals['_BIDIRECTIONAL_REQUEST']._serialized_start=210
  _globals['_BIDIRECTIONAL_REQUEST']._serialized_end=245
  _globals['_BIDIRECTIONAL_RESPONSE']._serialized_start=247
  _globals['_BIDIRECTIONAL_RESPONSE']._serialized_end=286
  _globals['_TESTLEARN']._serialized_start=289
  _globals['_TESTLEARN']._serialized_end=575
# @@protoc_insertion_point(module_scope)
