# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import test_pb2 as test__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in test_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TestLearnStub(object):
    """定义服务，这是Grpc的核心
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Test1 = channel.unary_unary(
                '/test.TestLearn/Test1',
                request_serializer=test__pb2.test1_request.SerializeToString,
                response_deserializer=test__pb2.test1_response.FromString,
                _registered_method=True)
        self.server_stream = channel.unary_stream(
                '/test.TestLearn/server_stream',
                request_serializer=test__pb2.server_request.SerializeToString,
                response_deserializer=test__pb2.server_response.FromString,
                _registered_method=True)
        self.client_stream = channel.stream_unary(
                '/test.TestLearn/client_stream',
                request_serializer=test__pb2.client_request.SerializeToString,
                response_deserializer=test__pb2.client_response.FromString,
                _registered_method=True)
        self.bidirectional_stream = channel.stream_stream(
                '/test.TestLearn/bidirectional_stream',
                request_serializer=test__pb2.bidirectional_request.SerializeToString,
                response_deserializer=test__pb2.bidirectional_response.FromString,
                _registered_method=True)


class TestLearnServicer(object):
    """定义服务，这是Grpc的核心
    """

    def Test1(self, request, context):
        """1，简单 一元 RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def server_stream(self, request, context):
        """2, 服务端流式 RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def client_stream(self, request_iterator, context):
        """3, 客户端流式 RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def bidirectional_stream(self, request_iterator, context):
        """4, 双向流式 RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestLearnServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Test1': grpc.unary_unary_rpc_method_handler(
                    servicer.Test1,
                    request_deserializer=test__pb2.test1_request.FromString,
                    response_serializer=test__pb2.test1_response.SerializeToString,
            ),
            'server_stream': grpc.unary_stream_rpc_method_handler(
                    servicer.server_stream,
                    request_deserializer=test__pb2.server_request.FromString,
                    response_serializer=test__pb2.server_response.SerializeToString,
            ),
            'client_stream': grpc.stream_unary_rpc_method_handler(
                    servicer.client_stream,
                    request_deserializer=test__pb2.client_request.FromString,
                    response_serializer=test__pb2.client_response.SerializeToString,
            ),
            'bidirectional_stream': grpc.stream_stream_rpc_method_handler(
                    servicer.bidirectional_stream,
                    request_deserializer=test__pb2.bidirectional_request.FromString,
                    response_serializer=test__pb2.bidirectional_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test.TestLearn', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('test.TestLearn', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TestLearn(object):
    """定义服务，这是Grpc的核心
    """

    @staticmethod
    def Test1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/test.TestLearn/Test1',
            test__pb2.test1_request.SerializeToString,
            test__pb2.test1_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def server_stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/test.TestLearn/server_stream',
            test__pb2.server_request.SerializeToString,
            test__pb2.server_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def client_stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/test.TestLearn/client_stream',
            test__pb2.client_request.SerializeToString,
            test__pb2.client_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def bidirectional_stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/test.TestLearn/bidirectional_stream',
            test__pb2.bidirectional_request.SerializeToString,
            test__pb2.bidirectional_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
