# Generated by Django 6.0.2 on 2026-03-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_customer_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, '状态1'), (2, '状态2'), (3, '状态3'), (4, '状态4'), (5, '状态5')], verbose_name='状态')),
            ],
            options={
                'verbose_name': '状态测试表',
                'verbose_name_plural': '状态测试表',
            },
        ),
    ]
