# Generated by Django 6.0.2 on 2026-03-01 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.customer'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='testmodel',
            table='test_model',
        ),
    ]
