# Generated by Django 6.0.2 on 2026-03-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_testmodel_customer_alter_testmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testmodel',
            table=None,
        ),
    ]
