# Generated by Django 6.0.2 on 2026-03-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_testmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testmodel',
            table='test_model',
        ),
    ]
